steps:
  - label: "build binary"
    command: "./scripts/build.sh"
    artifact_paths: "dist/hello"
    plugins:
      - docker#v3.13.0:
          image: "golang:1.18.0"

  - input: "Who is running this script?"
    key: "collect-name"
    fields:
      - text: "Your name"
        key: "name"

  - label: "run binary"
    key: "run-binary"
    command: "./scripts/run.sh"
    depends_on: "collect-name"
    artifact_paths: "output.txt"
    plugins:
      - 'uber-workflow/run-without-clone':

  - label: "validate output"
    command: "./scripts/test.sh"
    depends_on: "run-binary"
    artifact_paths: "output.txt"
    plugins:
      - 'uber-workflow/run-without-clone':